name: bEMRApps
options:
  minimumXcodeGenVersion: 2.30.0
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
    watchOS: "10.0"
  usesTabs: false
packages:
  bEMR:
    path: .
targets:
  EMRiOSApp:
    type: application
    platform: iOS
    sources:
      - path: Apps/EMRiOS
    resources:
      - path: Apps/EMRiOS/Assets.xcassets
    info:
      path: Support/Info_iOS.plist
    dependencies:
      - package: bEMR
        product: AppSharedUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.bemr.ios
  EMRiPadOS:
    type: application
    platform: iOS
    sources:
      - path: Apps/EMRiPadOS
    resources:
      - path: Apps/EMRiPadOS/Assets.xcassets
    info:
      path: Support/Info_iOS.plist
    dependencies:
      - package: bEMR
        product: AppSharedUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.bemr.ipados
        TARGETED_DEVICE_FAMILY: 2 # iPad only
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  EMRMac:
    type: application
    platform: macOS
    sources:
      - path: Apps/EMRMac
    resources:
      - path: Apps/EMRMac/Assets.xcassets
    info:
      path: Support/Info_macOS.plist
    dependencies:
      - package: bEMR
        product: AppSharedUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.bemr.mac
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  EMRWatch:
    type: application
    platform: watchOS
    sources:
      - path: Apps/EMRWatch
    info:
      path: Support/Info_watchOS.plist
    dependencies:
      - package: bEMR
        product: AppSharedUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.bemr.watch
schemes:
  EMRiOSApp:
    shared: true
    build:
      targets:
        EMRiOSApp: all
    run:
      config: Debug
  EMRiPadOS:
    shared: true
    build:
      targets:
        EMRiPadOS: all
    run:
      config: Debug
  EMRMac:
    shared: true
    build:
      targets:
        EMRMac: all
    run:
      config: Debug
  EMRWatch:
    shared: true
    build:
      targets:
        EMRWatch: all
    run:
      config: Debug
